# Generated by Django 5.2.3 on 2025-09-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_controlled_lists", "0006_update_spatial_view_reference_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitemvalue",
            name="value",
            field=models.TextField(blank=True),
        ),
    ]
