# Generated by Django 4.2.23 on 2025-08-01 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("models", "11499_add_editlog_resourceinstance_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="WidgetMapping",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("component", models.CharField(max_length=255, unique=True)),
                (
                    "widget",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="models.widget"
                    ),
                ),
            ],
        ),
    ]
