version: 2
updates:
- package-ecosystem: pip
  directory: "/arches/install"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pillow
    versions:
    - 8.0.1
    - 8.1.0
  - dependency-name: django
    versions:
    - 3.1.4
    - 3.1.5
  - dependency-name: django-cors-headers
    versions:
    - 3.6.0
  - dependency-name: django-oauth-toolkit
    versions:
    - 1.3.3
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jqtree
    versions:
    - 1.5.2
    - 1.5.3
  - dependency-name: ionicons
    versions:
    - 5.2.3
    - 5.4.0
  - dependency-name: "@mapbox/mapbox-gl-draw"
    versions:
    - 1.2.0
