linters:
  pep8:
    python: 3
    ignore: 'W503,E402,E203'
    max-line-length: 140
    fixer: false
  black:
    config: ./pyproject.toml
    fixer: true
  eslint:
    config: './arches/.eslintrc.js'
files:
  ignore:
    - 'arches/app/media/packages/*'
    - 'node_modules/*'
review:
  fail_on_comments: true
fixers:
  enable: true
