version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: ~/arches/install/ubuntu_tusty_setup.sh
      timeout: 300
      runas: root
    - location: ~/arches/install/install_arches.sh
      timeout: 300
      runas: root
