version: '2'
services:

    archesback:
      container_name: archesback
      image: archesproject/arches:latest
      build:
        context: .
        dockerfile: ./Dockerfile
      command: run_arches
      volumes:
        - archesback-log:/arches/arches/logs
        - archesback-static:/static_root
        - ../development_project_test:/web_root/development_project_test
        - ./:/web_root/arches
        - ./docker/settings_local.py:/web_root/arches/arches/settings_local.py
      environment:
        - ARCHES_PROJECT=development_project_test
        - INSTALL_DEFAULT_GRAPHS=True
        - INSTALL_DEFAULT_CONCEPTS=True
        - PGUSERNAME=postgres
        - PGPASSWORD=postgres
        - PGDBNAME=development_project_test
        - PGHOST=db
        - PGPORT=5432
        - ESHOST=elasticsearch
        - ESPORT=9200
        - ELASTICSEARCH_PREFIX=development_project_test
        - DJANGO_MODE=DEV
        - DJANGO_DEBUG=True
        # - DJANGO_REMOTE_DEBUG=True
        - DOMAIN_NAMES=localhost 192.168.1.116
        - TZ=PST
      ports:
        - '8000:8000'
      depends_on:
        - db
        - elasticsearch


    nginxback:
      container_name: nginxback
      image: cvast/cvast-nginx:1.2.0
      restart: unless-stopped
      ports:
        - '81:80'
        - '444:443'
      volumes:
        - archesback-static:/www/static
        - letsencryptback-acme-challenge:/var/www
        - letsencryptback:/etc/letsencrypt
      environment:
        - NGINX_PROXY_MODE=local
        - NGINX_PROTOCOL=http
        - LOCAL_PROXY_HOST=archesback
        - LOCAL_PROXY_PORT=8000
        - DOMAIN_NAMES=localhost 192.168.1.116
        - PUBLIC_MODE=False
        - TZ=PST
      depends_on:
        - archesback

    db:
      container_name: db
      image: mdillon/postgis:9.6-alpine
      volumes:
          - postgres-data:/var/lib/postgresql/data
          - postgres-log:/var/log/postgresql
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_PASSWORD=postgres
        - TZ=PST


    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:5.2
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - TZ=PST


    letsencryptback:
      container_name: letsencryptback
      image: cvast/cvast-letsencrypt:1.1
      volumes:
        - letsencryptback-acme-challenge:/var/www
        - letsencryptback:/etc/letsencrypt
        - letsencryptback-log:/var/log/letsencrypt
      command: get_certificate
      environment:
        - MODE=regular
        - LETSENCRYPT_EMAIL=info@example.com
        - DOMAIN_NAMES=localhost 192.168.1.116
        - PRODUCTION_MODE=False
        - PERSISTENT_MODE=True
        - TZ=PST


volumes:
    archesback-log:
    archesback-static:
    archesback-bowercomponents:
    postgres-data:
    postgres-log:
    elasticsearch-data:
    letsencryptback:
    letsencryptback-log:
    letsencryptback-acme-challenge:
