# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-25 11:36
from __future__ import unicode_literals

import os
from django.db import migrations, models
from django.core import management
from arches.app.models.system_settings import settings

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    extensions = [os.path.join(settings.ONTOLOGY_PATH, x) for x in settings.ONTOLOGY_EXT]
    management.call_command('load_ontology', source=os.path.join(settings.ONTOLOGY_PATH, settings.ONTOLOGY_BASE),
        version=settings.ONTOLOGY_BASE_VERSION, ontology_name=settings.ONTOLOGY_BASE_NAME, id=settings.ONTOLOGY_BASE_ID, extensions=','.join(extensions), verbosity=0)

def reverse_func(apps, schema_editor):
    extensions = [os.path.join(settings.ONTOLOGY_PATH, x) for x in settings.ONTOLOGY_EXT]
    management.call_command('load_ontology', source=os.path.join(settings.ONTOLOGY_PATH, settings.ONTOLOGY_BASE),
        version=settings.ONTOLOGY_BASE_VERSION, ontology_name=settings.ONTOLOGY_BASE_NAME, id=settings.ONTOLOGY_BASE_ID, extensions=','.join(extensions), verbosity=0)

class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_4_0_1'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO widgets(
                widgetid,
                name,
                component,
                datatype,
                defaultconfig
            ) VALUES (
                '31f3728c-7613-11e7-a139-784f435179ea',
                'resource-instance-select-widget',
                'views/components/widgets/resource-instance-select',
                'resource-instance',
                '{
                    "placeholder": ""
                }'
            );

            INSERT INTO d_data_types VALUES (
                    'resource-instance',
                    'fa fa-external-link-o',
                    'datatypes.py',
                    'ResourceInstanceDataType',
                    '{
                        "graphid": null
                    }',
                    'views/components/datatypes/resource-instance',
                    'resource-instance-datatype-config',
                    FALSE,
                    '31f3728c-7613-11e7-a139-784f435179ea',
                    TRUE
            );

            INSERT INTO widgets(
                widgetid,
                name,
                component,
                datatype,
                defaultconfig
            ) VALUES (
                'ff3c400a-76ec-11e7-a793-784f435179ea',
                'resource-instance-multiselect-widget',
                'views/components/widgets/resource-instance-multiselect',
                'resource-instance-list',
                '{
                    "placeholder": ""
                }'
            );

            INSERT INTO d_data_types VALUES (
                    'resource-instance-list',
                    'fa fa-external-link-square',
                    'datatypes.py',
                    'ResourceInstanceDataType',
                    '{
                        "graphid": null
                    }',
                    'views/components/datatypes/resource-instance',
                    'resource-instance-datatype-config',
                    FALSE,
                    'ff3c400a-76ec-11e7-a793-784f435179ea',
                    TRUE
            );
            """,
            """
            DELETE FROM d_data_types
                WHERE datatype = 'resource-instance';

            DELETE from widgets
                WHERE widgetid = '31f3728c-7613-11e7-a139-784f435179ea';

            DELETE FROM d_data_types
                WHERE datatype = 'resource-instance-list';

            DELETE from widgets
                WHERE widgetid = 'ff3c400a-76ec-11e7-a793-784f435179ea';
        """),
        migrations.RunSQL("""
            UPDATE public.nodes
               SET ontologyclass='E93_Presence'
             WHERE ontologyclass='E94_Space';

            UPDATE public.edges
               SET ontologyproperty='P167i_was_place_of'
             WHERE ontologyproperty='P167i_was_place_at';

            UPDATE public.edges
               SET ontologyproperty='P167i_was_place_of'
             WHERE ontologyproperty='P168_place_is_defined_by';

            UPDATE public.edges
               SET ontologyproperty='P167_was_at'
             WHERE ontologyproperty='P168i_defines_place';
            """,
            """
            UPDATE public.nodes
               SET ontologyclass='E94_Space'
             WHERE ontologyclass='E93_Presence';

            UPDATE public.edges
               SET ontologyproperty='P168_place_is_defined_by'
             WHERE ontologyproperty='P167i_was_place_of';

            UPDATE public.edges
               SET ontologyproperty='P168i_defines_place'
             WHERE ontologyproperty='P167_was_at';

            UPDATE public.edges
               SET ontologyproperty='P167i_was_place_at'
             WHERE ontologyproperty='P167i_was_place_of';
        """),
        migrations.RunPython(forwards_func, reverse_func),
                migrations.AlterField(
                    model_name='function',
                    name='component',
                    field=models.TextField(blank=True, null=True, unique=True),
                ),
                migrations.AlterField(
                    model_name='geocoder',
                    name='component',
                    field=models.TextField(unique=True),
                ),
                migrations.AlterField(
                    model_name='geocoder',
                    name='name',
                    field=models.TextField(unique=True),
                ),
                migrations.AlterField(
                    model_name='widget',
                    name='component',
                    field=models.TextField(unique=True),
                ),
                migrations.AlterField(
                    model_name='widget',
                    name='name',
                    field=models.TextField(unique=True),
                ),
    ]
