# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_4_0_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileProjectXCard',
            fields=[
                ('mobile_project_x_card_id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.CardModel')),
                ('mobile_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.MobileProject')),
            ],
            options={
                'db_table': 'mobile_projects_x_cards',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='mobileproject',
            name='cards',
            field=models.ManyToManyField(through='models.MobileProjectXCard', to='models.CardModel'),
        ),
        migrations.AlterUniqueTogether(
            name='mobileprojectxcard',
            unique_together=set([('mobile_project', 'card')]),
        ),
    ]
