# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0013_4_0_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSurveyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'mobile_surveys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MobileSurveyXCard',
            fields=[
                ('mobile_survey_x_card_id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('sortorder', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.CardModel')),
                ('mobile_survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.MobileSurveyModel')),
            ],
            options={
                'db_table': 'mobile_surveys_x_cards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MobileSurveyXGroup',
            fields=[
                ('mobile_survey_x_group_id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('mobile_survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.MobileSurveyModel')),
            ],
            options={
                'db_table': 'mobile_surveys_x_groups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MobileSurveyXUser',
            fields=[
                ('mobile_survey_x_user_id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('mobile_survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.MobileSurveyModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mobile_surveys_x_users',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='mobileproject',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='mobileproject',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='mobileproject',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='mobileproject',
            name='lasteditedby',
        ),
        migrations.RemoveField(
            model_name='mobileproject',
            name='users',
        ),
        migrations.AlterUniqueTogether(
            name='mobileprojectxcard',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='mobileprojectxcard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='mobileprojectxcard',
            name='mobile_project',
        ),
        migrations.AlterUniqueTogether(
            name='mobileprojectxgroup',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='mobileprojectxgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='mobileprojectxgroup',
            name='mobile_project',
        ),
        migrations.AlterUniqueTogether(
            name='mobileprojectxuser',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='mobileprojectxuser',
            name='mobile_project',
        ),
        migrations.RemoveField(
            model_name='mobileprojectxuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='MobileProject',
        ),
        migrations.DeleteModel(
            name='MobileProjectXCard',
        ),
        migrations.DeleteModel(
            name='MobileProjectXGroup',
        ),
        migrations.DeleteModel(
            name='MobileProjectXUser',
        ),
        migrations.AddField(
            model_name='mobilesurveymodel',
            name='cards',
            field=models.ManyToManyField(through='models.MobileSurveyXCard', to='models.CardModel'),
        ),
        migrations.AddField(
            model_name='mobilesurveymodel',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilesurveymodel',
            name='groups',
            field=models.ManyToManyField(through='models.MobileSurveyXGroup', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='mobilesurveymodel',
            name='lasteditedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasteditedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilesurveymodel',
            name='users',
            field=models.ManyToManyField(through='models.MobileSurveyXUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MobileSurvey',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('models.mobilesurveymodel',),
        ),
        migrations.AlterUniqueTogether(
            name='mobilesurveyxuser',
            unique_together=set([('mobile_survey', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='mobilesurveyxgroup',
            unique_together=set([('mobile_survey', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='mobilesurveyxcard',
            unique_together=set([('mobile_survey', 'card')]),
        ),
    ]
