# Generated by Django 4.2.4 on 2023-09-13 10:19

import arches.app.utils.storage_filename_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '9944_update_refresh_relationship_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to=arches.app.utils.storage_filename_generator.generate_filename),
        ),
    ]
