# Generated by Django 4.2.5 on 2023-10-11 12:52

from django.db import migrations


def assign_view_plugin(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    view_plugin = Permission.objects.get(codename="view_plugin")
    resource_reviewers = Group.objects.get(name="Resource Reviewer")
    resource_reviewers.permissions.add(view_plugin)


def remove_view_plugin(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    view_plugin = Permission.objects.get(codename="view_plugin")
    resource_reviewers = Group.objects.get(name="Resource Reviewer")
    resource_reviewers.permissions.remove(view_plugin)


class Migration(migrations.Migration):
    dependencies = [
        ("models", "10097_add_editlog_index"),
    ]

    operations = [
        migrations.RunPython(assign_view_plugin, remove_view_plugin),
    ]
