# Generated by Django 3.2.20 on 2023-09-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10041_limit_number_of_bulk_edit"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="editlog",
            index=models.Index(
                fields=["transactionid"], name="edit_log_transac_34aa75_idx"
            ),
        ),
    ]
