# Generated by Django 4.2.5 on 2023-10-16 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("models", "10120_replace_whole_word_bulk_edit"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowHistory",
            fields=[
                ("workflowid", models.UUIDField(primary_key=True, serialize=False)),
                ("stepdata", models.JSONField(default=dict)),
                ("componentdata", models.JSONField(default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="userid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow_history",
                "managed": True,
            },
        ),
    ]
