# Generated by Django 4.2.4 on 2023-10-17 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("models", "9973_bulk_deleting_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowhistory",
            name="workflowname",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="workflowhistory",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, null=False),
        ),
    ]
