# Generated by Django 4.2.4 on 2023-10-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '10121_workflowhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowhistory',
            name='workflowname',
            field=models.TextField(default=None, null=True),
        ),
    ]
