# Generated by Django 4.2.4 on 2023-10-23 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("models", "10149_add_workflow_name_to_workflow_history"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE widgets
            SET defaultconfig = jsonb_set(defaultconfig, '{defaultValue}', '[]')
            WHERE name = 'file-widget';
            """,
            reverse_sql="""
            UPDATE widgets
            SET defaultconfig = defaultconfig - 'defaultValue'
            WHERE name = 'file-widget';
            """,
        ),
    ]
