# Generated by Django 4.2.4 on 2023-10-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10150_add_default_value_file_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowhistory",
            name="workflowname",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
