# Generated by Django 4.2.10 on 2024-03-22 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '10515_i18n_plugins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spatialview',
            old_name='geometrynodeid',
            new_name='geometrynode',
        ),
        migrations.AddField(
            model_name='spatialview',
            name='language',
            field=models.ForeignKey(db_column='languageid', default='en', on_delete=django.db.models.deletion.CASCADE, to='models.language', to_field='code'),
            preserve_default=False,
        ),
    ]
