# Generated by Django 4.2.10 on 2024-02-21 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("models", "10541_controlled_list_manager"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="controlledlist",
            table="controlled_lists",
        ),
        migrations.AlterModelTable(
            name="controlledlistitem",
            table="controlled_list_items",
        ),
        migrations.AlterModelTable(
            name="controlledlistitemlabel",
            table="controlled_list_item_labels",
        ),
    ]
