# Generated by Django 4.2.11 on 2024-04-24 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10553_loosen_uri_uniqueness"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlledListItemImage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("value", models.FileField(upload_to="controlled_list_item_images")),
            ],
            options={
                "db_table": "controlled_list_item_labels",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ControlledListItemImageMetadata",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "metadata_type",
                    models.CharField(
                        choices=[("title", "Title"), ("desc", "Description"), ("attr", "Attribution"), ("alt", "Alternative text")],
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=2048)),
            ],
            options={
                "db_table": "controlled_list_item_image_metadata",
            },
        ),
        migrations.AlterField(
            model_name="controlledlistitemlabel",
            name="language",
            field=models.ForeignKey(
                db_column="languageid", null=True, on_delete=django.db.models.deletion.PROTECT, to="models.language", to_field="code"
            ),
        ),
        migrations.AlterField(
            model_name="controlledlistitemlabel",
            name="value_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("category__in", ("label", "image"))),
                on_delete=django.db.models.deletion.PROTECT,
                to="models.dvaluetype",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlledlistitemlabel",
            constraint=models.CheckConstraint(
                check=models.Q(("language_id__isnull", False), ("value_type", "image"), _connector="OR"),
                name="only_images_nullable_language",
            ),
        ),
        migrations.AddField(
            model_name="controlledlistitemimagemetadata",
            name="controlled_list_item_image",
            field=models.ForeignKey(
                db_column="labelid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controlled_list_item_image_metadata",
                to="models.controlledlistitemlabel",
            ),
        ),
        migrations.AddField(
            model_name="controlledlistitemimagemetadata",
            name="language",
            field=models.ForeignKey(
                db_column="languageid", on_delete=django.db.models.deletion.PROTECT, to="models.language", to_field="code"
            ),
        ),
        migrations.AddConstraint(
            model_name="controlledlistitemimagemetadata",
            constraint=models.UniqueConstraint(
                fields=("controlled_list_item_image", "value", "metadata_type", "language"), name="unique_image_metadata_valuetype_language"
            ),
        ),
    ]
