# Generated by Django 4.2.10 on 2024-02-23 08:33

from django.db import migrations, models
import django.db.models.fields.json
import django.db.models.functions.comparison


class Migration(migrations.Migration):
    dependencies = [
        ("models", "10552_add_reference_datatype"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                django.db.models.functions.comparison.Cast(
                    django.db.models.fields.json.KeyTextTransform("controlledList", "config"),
                    output_field=models.UUIDField(null=True)
                ),
                name="lists_reffed_by_node_idx",
            ),
        ),
    ]
