# Generated by Django 4.2.11 on 2024-04-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10552_add_reference_datatype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlledlistitem",
            name="uri",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddConstraint(
            model_name="controlledlistitem",
            constraint=models.UniqueConstraint(fields=("controlled_list", "uri"), name="unique_list_uri"),
        ),
    ]
