# Generated by Django 4.2.11 on 2024-04-24 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10554_controlled_list_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlledListItemValue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=1024)),
                (
                    "controlled_list_item",
                    models.ForeignKey(
                        db_column="itemid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controlled_list_item_values",
                        to="models.controlledlistitem",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        db_column="languageid",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="models.language",
                        to_field="code",
                    ),
                ),
                (
                    "valuetype",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("category__in", ("label", "image"))),
                        on_delete=django.db.models.deletion.PROTECT,
                        to="models.dvaluetype",
                    ),
                ),
            ],
            options={
                "db_table": "controlled_list_item_values",
            },
        ),
        migrations.AlterField(
            model_name="controlledlistitemimagemetadata",
            name="controlled_list_item_image",
            field=models.ForeignKey(
                db_column="labelid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controlled_list_item_image_metadata",
                to="models.controlledlistitemimage",
            ),
        ),
        migrations.AlterModelTable(
            name="controlledlistitemimage",
            table="controlled_list_item_values",
        ),
        migrations.DeleteModel(
            name="ControlledListItemLabel",
        ),
        migrations.AddConstraint(
            model_name="controlledlistitemvalue",
            constraint=models.UniqueConstraint(
                fields=("controlled_list_item", "value", "valuetype", "language"), name="unique_item_value_valuetype_language"
            ),
        ),
        migrations.AddConstraint(
            model_name="controlledlistitemvalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("valuetype", "prefLabel")),
                fields=("controlled_list_item", "language"),
                name="unique_item_preflabel_language",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlledlistitemvalue",
            constraint=models.CheckConstraint(
                check=models.Q(("language_id__isnull", False), ("valuetype", "image"), _connector="OR"),
                name="only_images_nullable_language",
            ),
        ),
    ]
