# Generated by Django 4.2.10 on 2024-02-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "10553_lists_reffed_by_node_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlledlist",
            name="search_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="controlledlistitem",
            name="guide",
            field=models.BooleanField(default=False),
        ),
    ]
