# Generated by Django 4.2.11 on 2024-04-15 15:14

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10774_deduplicate_language_codes"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("code"), name="case_insensitive_code"),
        ),
    ]
