# Generated by Django 4.2.15 on 2024-08-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10804_core_search_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodegroup",
            name="graph",
            field=models.ForeignKey(
                blank=True,
                db_column="graphid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.graphmodel",
            ),
        ),
    ]
