# Generated by Django 5.1.1 on 2024-09-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10476_add_user_bulk_data_import"),
    ]

    def remove_placeholder_from_i18n_properties(apps, schema_editor):
        Widget = apps.get_model("models", "Widget")
        for widget in Widget.objects.filter(
            datatype="non-localized-string", defaultconfig__has_key="i18n_properties"
        ):
            try:
                widget.defaultconfig["i18n_properties"].remove("placeholder")
            except ValueError:
                pass
            else:
                widget.save()

    def restore_placeholder_into_i18n_properties(apps, schema_editor):
        Widget = apps.get_model("models", "Widget")
        for widget in Widget.objects.filter(datatype="non-localized-string"):
            i18n_props = widget.defaultconfig["i18n_properties"]
            if "placeholder" not in i18n_props:
                i18n_props.append("placeholder")
                widget.save()

    operations = [
        migrations.RunPython(
            remove_placeholder_from_i18n_properties,
            restore_placeholder_into_i18n_properties,
        ),
    ]
