# Generated by Django 4.2.14 on 2024-07-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10883_etl_collections_to_controlled_lists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlledlistitem",
            name="uri",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
