# Generated by Django 5.1.2 on 2024-10-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11043_tile_nodegroup_add_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceinstance",
            name="resourceinstanceid",
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tilemodel",
            name="tileid",
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
    ]
