# Generated by Django 5.1.3 on 2024-11-07 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11045_generate_resource_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tilemodel",
            name="resourceinstance",
            field=models.ForeignKey(
                db_column="resourceinstanceid",
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.resourceinstance",
            ),
        ),
    ]
