# Generated by Django 5.1.2 on 2024-10-25 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10437_node_alias_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodegroup",
            name="parentnodegroup",
            field=models.ForeignKey(
                blank=True,
                db_column="parentnodegroupid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                related_query_name="child",
                to="models.nodegroup",
            ),
        ),
        migrations.AlterField(
            model_name="tilemodel",
            name="parenttile",
            field=models.ForeignKey(
                blank=True,
                db_column="parenttileid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                related_query_name="child",
                to="models.tilemodel",
            ),
        ),
    ]
