# Generated by Django 5.1.2 on 2024-10-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11043_tile_nodegroup_add_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceinstance",
            name="resourceinstanceid",
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tilemodel",
            name="tileid",
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="resourceinstance",
            name="graph",
            field=models.ForeignKey(
                blank=True,
                db_column="graphid",
                on_delete=models.deletion.CASCADE,
                to="models.graphmodel",
            ),
        ),
        migrations.AlterField(
            model_name="resourceinstance",
            name="resource_instance_lifecycle_state",
            field=models.ForeignKey(
                blank=True,
                on_delete=models.deletion.PROTECT,
                related_name="resource_instances",
                to="models.resourceinstancelifecyclestate",
            ),
        ),
    ]
