# Generated by Django 5.1.3 on 2024-11-06 12:10

import arches.app.models.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11044_make_further_fields_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceinstance",
            name="resourceinstanceid",
            field=models.UUIDField(
                blank=True,
                db_default=arches.app.models.functions.UUID4(),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
