# Generated by Django 2.2.6 on 2019-12-13 11:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10705_spatialviews_internationalisation_support"),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE d_data_types set issearchable = true WHERE datatype = 'file-list' OR datatype = 'geojson-feature-collection'",
            reverse_sql="UPDATE d_data_types set issearchable = false WHERE datatype = 'file-list' OR datatype = 'geojson-feature-collection'",
        ),
    ]
