# Generated by Django 4.2.15 on 2024-08-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "9053_add_future_graphs"),
    ]

    sql = """
    UPDATE node_groups
    SET graphid = sub.graphid
    FROM (
        SELECT DISTINCT ng.nodegroupid, n.graphid
        FROM nodes n
        JOIN node_groups ng ON n.nodegroupid = ng.nodegroupid
    ) AS sub
    WHERE node_groups.nodegroupid = sub.nodegroupid;
    """

    reverse_sql = """"""

    operations = [
        migrations.AddField(
            model_name="nodegroup",
            name="graph",
            field=models.ForeignKey(
                blank=True,
                db_column="graphid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="models.graphmodel",
            ),
        ),
        migrations.RunSQL(
            sql,
            reverse_sql,
        ),
    ]
