# Generated by Django 5.1 on 2024-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '10437_node_alias_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadstaging',
            name='sortorder',
            field=models.IntegerField(default=0),
        ),
    ]
