# Generated by Django 4.2.11 on 2024-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10476_add_user_bulk_data_import"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="editlog",
            index=models.Index(
                fields=["resourceinstanceid"], name="edit_log_resourc_d0371e_idx"
            ),
        ),
    ]
