# Generated by Django 5.2 on 2025-04-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11882_principal_user_read_only"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="graphmodel",
            constraint=models.UniqueConstraint(
                fields=("slug", "source_identifier"), name="unique_slug"
            ),
        ),
    ]
