# Generated by Django 5.2b1 on 2025-03-13 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11570_harden_editable_future_graphs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spatialview",
            name="slug",
            field=models.TextField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="nomatch",
                        message="Slug must contain only letters, numbers and underscores, but not begin with a number.",
                        regex="^[a-zA-Z_]([a-zA-Z0-9_]+)$",
                    )
                ],
            ),
        ),
    ]
