# Generated by Django 5.2b1 on 2025-02-21 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10959_update_uuid_defaults_to_v4"),
    ]

    operations = [
        migrations.AddField(
            model_name="tilemodel",
            name="nodegroup",
            field=models.ForeignObject(
                from_fields=["nodegroup_id"],
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tiles",
                related_query_name="tile",
                to="models.nodegroup",
                to_fields=["nodegroupid"],
            ),
        ),
    ]
