# Generated by Django 5.2.dev20250109163842 on 2025-01-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11725_add_blank_and_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tilemodel",
            name="data",
            field=models.JSONField(blank=True, db_column="tiledata", default=dict),
        ),
    ]
