# Generated by Django 5.2b1 on 2025-02-21 13:44

import django.db.models.deletion
from django.db import migrations
import arches.app.models.fields.foreign


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11725_make_tiledata_not_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="tilemodel",
            name="nodegroup",
            field=arches.app.models.fields.foreign.GhostableForeignObject(
                from_fields=["nodegroup_id"],
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tiles",
                related_query_name="tile",
                to="models.nodegroup",
                to_fields=["nodegroupid"],
            ),
        ),
    ]
