# Generated by Django 5.2.dev20250109163842 on 2025-01-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11613_nodegroup_grouping_node_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceinstance",
            name="graph",
            field=models.ForeignKey(
                blank=True,
                db_column="graphid",
                on_delete=django.db.models.deletion.CASCADE,
                to="models.graphmodel",
            ),
        ),
        migrations.AlterField(
            model_name="resourceinstance",
            name="resource_instance_lifecycle_state",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resource_instances",
                to="models.resourceinstancelifecyclestate",
            ),
        ),
        migrations.AlterField(
            model_name="resourceinstance",
            name="resourceinstanceid",
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tilemodel",
            name="parenttile",
            field=models.ForeignKey(
                blank=True,
                db_column="parenttileid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                related_query_name="child",
                to="models.tilemodel",
            ),
        ),
        migrations.AlterField(
            model_name="tilemodel",
            name="tileid",
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
    ]
