# Generated by Django 5.2b1 on 2025-03-19 11:14

import django.core.validators
import re
from django.db import migrations, models
from slugify import slugify

class Migration(migrations.Migration):

    dependencies = [
        ("models", "11857_spatial_view_source_identifier_filter"),
    ]

    def add_missing_graph_slug(apps, schema_editor):
        Graph = apps.get_model("models", "GraphModel")
        graphs_missing_slug = Graph.objects.filter(slug__isnull=True)
        for graph in graphs_missing_slug:
            graph.slug = slugify(str(graph.name), separator="_")
            graph.save()

    operations = [
        migrations.RunPython(
            add_missing_graph_slug,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="graphmodel",
            name="slug",
            field=models.TextField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
