# Generated by Django 5.2b1 on 2025-03-19 11:14

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11857_spatial_view_source_identifier_filter"),
    ]

    forward_sql = """
        UPDATE graphs
        SET slug = __arches_slugify(name ->> 'en')
        WHERE slug IS NULL OR slug = '';
    """

    operations = [
        migrations.RunSQL(
            forward_sql,
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="graphmodel",
            name="slug",
            field=models.TextField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
