# Generated by Django 5.2 on 2025-05-06 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11799_require_graph_slug"),
    ]

    operations = [
        migrations.operations.special.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="tilemodel",
                    name="nodegroup_id",
                ),
                migrations.AlterField(
                    model_name="tilemodel",
                    name="nodegroup",
                    field=models.ForeignKey(
                        db_column="nodegroupid",
                        db_index=False,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tiles",
                        related_query_name="tile",
                        to="models.nodegroup",
                    ),
                ),
            ]
        ),
    ]
