# Generated by Django 5.2b1 on 2025-03-14 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11571_alter_spatialview_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spatialview",
            name="geometrynode",
            field=models.ForeignKey(
                db_column="geometrynodeid",
                limit_choices_to={
                    "datatype": "geojson-feature-collection",
                    "source_identifier__isnull": True,
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="models.node",
            ),
        ),
    ]
