# Generated by Django 5.2 on 2025-04-15 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11842_userpreferences"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resourcexresource",
            old_name="nodeid",
            new_name="node",
        ),
        migrations.RenameField(
            model_name="resourcexresource",
            old_name="resourceinstanceidfrom",
            new_name="resourceinstancefrom",
        ),
        migrations.RenameField(
            model_name="resourcexresource",
            old_name="resourceinstancefrom_graphid",
            new_name="resourceinstancefrom_graph",
        ),
        migrations.RenameField(
            model_name="resourcexresource",
            old_name="resourceinstanceidto",
            new_name="resourceinstanceto",
        ),
        migrations.RenameField(
            model_name="resourcexresource",
            old_name="resourceinstanceto_graphid",
            new_name="resourceinstanceto_graph",
        ),
        migrations.RenameField(
            model_name="resourcexresource",
            old_name="tileid",
            new_name="tile",
        ),
        migrations.AlterField(
            model_name="resourcexresource",
            name="node",
            field=models.ForeignKey(
                blank=True,
                db_column="nodeid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resxres",
                to="models.node",
            ),
        ),
        migrations.AlterField(
            model_name="resourcexresource",
            name="resourceinstancefrom",
            field=models.ForeignKey(
                blank=True,
                db_column="resourceinstanceidfrom",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resxres_from",
                to="models.resourceinstance",
            ),
        ),
        migrations.AlterField(
            model_name="resourcexresource",
            name="resourceinstancefrom_graph",
            field=models.ForeignKey(
                blank=True,
                db_column="resourceinstancefrom_graphid",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resxres_from",
                to="models.graphmodel",
            ),
        ),
        migrations.AlterField(
            model_name="resourcexresource",
            name="resourceinstanceto",
            field=models.ForeignKey(
                blank=True,
                db_column="resourceinstanceidto",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resxres_to",
                to="models.resourceinstance",
            ),
        ),
        migrations.AlterField(
            model_name="resourcexresource",
            name="resourceinstanceto_graph",
            field=models.ForeignKey(
                blank=True,
                db_column="resourceinstanceto_graphid",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resxres_to",
                to="models.graphmodel",
            ),
        ),
        migrations.AlterField(
            model_name="resourcexresource",
            name="tile",
            field=models.ForeignKey(
                blank=True,
                db_column="tileid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resxres",
                to="models.tilemodel",
            ),
        ),
    ]
