# Generated by Django 5.2 on 2025-04-15 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11873_model_ordering"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resourcexresource",
            old_name="nodeid",
            new_name="node",
        ),
        migrations.RenameField(
            model_name="resourcexresource",
            old_name="resourceinstanceidfrom",
            new_name="from_resource",
        ),
        migrations.RenameField(
            model_name="resourcexresource",
            old_name="resourceinstancefrom_graphid",
            new_name="from_resource_graph",
        ),
        migrations.RenameField(
            model_name="resourcexresource",
            old_name="resourceinstanceidto",
            new_name="to_resource",
        ),
        migrations.RenameField(
            model_name="resourcexresource",
            old_name="resourceinstanceto_graphid",
            new_name="to_resource_graph",
        ),
        migrations.RenameField(
            model_name="resourcexresource",
            old_name="tileid",
            new_name="tile",
        ),
        migrations.AlterField(
            model_name="resourcexresource",
            name="node",
            field=models.ForeignKey(
                blank=True,
                db_column="nodeid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resxres",
                to="models.node",
            ),
        ),
        migrations.AlterField(
            model_name="resourcexresource",
            name="from_resource",
            field=models.ForeignKey(
                blank=True,
                db_column="resourceinstanceidfrom",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_resxres",
                to="models.resourceinstance",
            ),
        ),
        migrations.AlterField(
            model_name="resourcexresource",
            name="from_resource_graph",
            field=models.ForeignKey(
                blank=True,
                db_column="resourceinstancefrom_graphid",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_resxres",
                to="models.graphmodel",
            ),
        ),
        migrations.AlterField(
            model_name="resourcexresource",
            name="to_resource",
            field=models.ForeignKey(
                blank=True,
                db_column="resourceinstanceidto",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_resxres",
                to="models.resourceinstance",
            ),
        ),
        migrations.AlterField(
            model_name="resourcexresource",
            name="to_resource_graph",
            field=models.ForeignKey(
                blank=True,
                db_column="resourceinstanceto_graphid",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_resxres",
                to="models.graphmodel",
            ),
        ),
        migrations.AlterField(
            model_name="resourcexresource",
            name="tile",
            field=models.ForeignKey(
                blank=True,
                db_column="tileid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resxres",
                to="models.tilemodel",
            ),
        ),
        migrations.RemoveField(
            model_name="resourcexresource",
            name="datestarted",
        ),
        migrations.RemoveField(
            model_name="resourcexresource",
            name="dateended",
        ),
    ]
