# Generated by Django 5.2rc1 on 2025-03-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11579_ids_search_filter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["sortorder"]},
        ),
        migrations.AlterModelOptions(
            name="cardmodel",
            options={"managed": True, "ordering": ["sortorder"]},
        ),
        migrations.AlterModelOptions(
            name="cardxnodexwidget",
            options={"managed": True, "ordering": ["sortorder"]},
        ),
        migrations.AlterModelOptions(
            name="etlmodule",
            options={"managed": True, "ordering": ["helpsortorder"]},
        ),
        migrations.AlterModelOptions(
            name="node",
            options={"managed": True, "ordering": ["sortorder"]},
        ),
        migrations.AlterModelOptions(
            name="plugin",
            options={"managed": True, "ordering": ["sortorder"]},
        ),
    ]
