# Generated by Django 5.2.2 on 2025-06-05 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12002_percent_sign_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphmodel",
            name="source_identifier",
            field=models.ForeignKey(
                blank=True,
                db_column="source_identifier",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft",
                to="models.graphmodel",
            ),
        ),
        migrations.AlterField(
            model_name="cardmodel",
            name="source_identifier",
            field=models.ForeignKey(
                blank=True,
                db_column="source_identifier",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft",
                to="models.cardmodel",
            ),
        ),
        migrations.AlterField(
            model_name="cardxnodexwidget",
            name="source_identifier",
            field=models.ForeignKey(
                blank=True,
                db_column="source_identifier",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft",
                to="models.cardxnodexwidget",
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="source_identifier",
            field=models.ForeignKey(
                blank=True,
                db_column="source_identifier",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft",
                to="models.edge",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="source_identifier",
            field=models.ForeignKey(
                blank=True,
                db_column="source_identifier",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft",
                to="models.node",
            ),
        ),
    ]
