# Generated by Django 5.2.2 on 2025-06-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12002_percent_sign_fix"),
    ]

    def set_active_true(apps, schema_editor):
        GraphModel = apps.get_model("models", "GraphModel")
        # Select published graphs without any draft graphs.
        GraphModel.objects.filter(
            # "graphmodel" is the default related_name for GraphModel.source_identifier
            graphmodel__isnull=True,
            publication__isnull=False,
        ).update(is_active=True)

    operations = [
        migrations.RunPython(set_active_true, migrations.RunPython.noop),
    ]
