# Generated by Django 5.2.1 on 2025-05-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11800_remove_foreign_object"),
    ]

    def fail_nicely_if_excess_widgets(apps, schema_editor):
        Node = apps.get_model("models", "Node")
        nodes_with_excess_widgets = Node.objects.annotate(
            source_widget_count=models.Count(
                "cardxnodexwidget", filter=models.Q(source_identifier__isnull=True)
            ),
            draft_widget_count=models.Count(
                "cardxnodexwidget", filter=models.Q(source_identifier__isnull=False)
            ),
        ).filter(
            models.Q(source_widget_count__gt=1) | models.Q(draft_widget_count__gt=1)
        )
        if nodes_with_excess_widgets.exists():
            raise Exception(
                "Nodes with excess widgets found. Run manage.py validate "
                "(optionally with --verbosity 2) to get a report. This must "
                "be fixed before migrations can resume."
            )

    operations = [
        migrations.RunPython(fail_nicely_if_excess_widgets, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="graphmodel",
            name="unique_slug",
        ),
        migrations.AlterUniqueTogether(
            name="cardxnodexwidget",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="cardxnodexwidget",
            constraint=models.UniqueConstraint(
                models.F("node"),
                condition=models.Q(("source_identifier__isnull", True)),
                name="unique_node_widget_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardxnodexwidget",
            constraint=models.UniqueConstraint(
                models.F("node"),
                condition=models.Q(("source_identifier__isnull", False)),
                name="unique_node_widget_draft",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphmodel",
            constraint=models.UniqueConstraint(
                models.F("slug"),
                condition=models.Q(("source_identifier__isnull", True)),
                name="unique_slug_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="graphmodel",
            constraint=models.UniqueConstraint(
                models.F("slug"),
                condition=models.Q(("source_identifier__isnull", False)),
                name="unique_slug_draft",
            ),
        ),
    ]
