# Generated by Django 5.2 on 2025-04-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11565_graphmodel_unique_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="resourceinstancelifecyclestatefromxref",
            constraint=models.UniqueConstraint(
                fields=(
                    "resource_instance_lifecycle_state_from",
                    "resource_instance_lifecycle_state_to",
                ),
                name="unique_lifecycle_state_fromxref",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceinstancelifecyclestatetoxref",
            constraint=models.UniqueConstraint(
                fields=(
                    "resource_instance_lifecycle_state_from",
                    "resource_instance_lifecycle_state_to",
                ),
                name="unique_lifecycle_state_toxref",
            ),
        ),
    ]
