# Generated by Django 5.2 on 2025-04-29 03:29

import arches.app.utils.storage_filename_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11869_rename_resxres_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="path",
            field=models.FileField(
                upload_to=arches.app.utils.storage_filename_generator.get_filename
            ),
        ),
    ]
