# Generated by Django 5.2 on 2025-05-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12023_tilemodel_index_nodegroup_and_resource"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                models.F("isdefault"),
                condition=models.Q(("isdefault", True)),
                name="single_default_language",
            ),
        ),
    ]
