# Generated by Django 5.2.1 on 2025-05-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12229_add_lifecycle_filter_to_standard_search"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tilemodel",
            index=models.Index(
                models.F("nodegroup"),
                models.F("resourceinstance"),
                name="nodegroup_and_resource",
            ),
        ),
    ]
