# Generated by Django 5.2.3 on 2025-06-20 08:44

import arches.app.models.fields.i18n
import arches.app.utils.betterJSONSerializer
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12009_language_single_default_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceinstance",
            name="descriptors",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="resourceinstance",
            name="graph_publication",
            field=models.ForeignKey(
                db_column="graphpublicationid",
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="models.graphxpublishedgraph",
            ),
        ),
        migrations.AlterField(
            model_name="resourceinstance",
            name="legacyid",
            field=models.TextField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="resourceinstance",
            name="name",
            field=arches.app.models.fields.i18n.I18n_TextField(
                blank=True,
                default="",
                editable=False,
                encoder=arches.app.utils.betterJSONSerializer.JSONSerializer,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resourceinstance",
            name="resource_instance_lifecycle_state",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resource_instances",
                to="models.resourceinstancelifecyclestate",
            ),
        ),
    ]
