# Generated by Django 5.2.4 on 2025-07-26 08:08

import django_migrate_sql.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12009_language_single_default_language"),
    ]

    reverse = """
                create or replace function __arches_instance_view_update() returns trigger as $$
                declare
                    view_namespace text;
                    model_id uuid;
                    instance_id uuid;
                    transaction_id uuid;
                    edit_type text;
                begin
                    view_namespace = format('%s.%s', tg_table_schema, tg_table_name);
                    select obj_description(view_namespace::regclass, 'pg_class') into model_id;
                    if (TG_OP = 'DELETE') then
                        delete from public.resource_instances where resourceinstanceid = old.resourceinstanceid;
                        insert into bulk_index_queue values (resourceinstanceid, current_timestamp) on conflict do nothing;
                        insert into edit_log (
                            resourceclassid,
                            resourceinstanceid,
                            edittype,
                            timestamp,
                            note,
                            transactionid
                        ) values (
                            model_id,
                            old.resourceinstanceid,
                            'delete',
                            now(),
                            'loaded via SQL backend',
                            public.uuid_generate_v1mc()
                        );
                        return old;
                    else
                        instance_id = new.resourceinstanceid;
                        if instance_id is null then
                            instance_id = public.uuid_generate_v1mc();
                        end if;

                        if (new.transactionid is null) then
                            transaction_id = public.uuid_generate_v1mc();
                        else
                            transaction_id = new.transactionid;
                        end if;

                        if (TG_OP = 'UPDATE') then
                            edit_type = 'edit';
                            if (transaction_id = old.transactionid) then
                                transaction_id = public.uuid_generate_v1mc();
                            end if;
                            update public.resource_instances
                            set createdtime = new.createdtime,
                                legacyid = new.legacyid
                            where resourceinstanceid = instance_id;
                        elsif (TG_OP = 'INSERT') then
                            edit_type = 'create';
                            insert into public.resource_instances(
                                resourceinstanceid,
                                graphid,
                                legacyid,
                                createdtime
                            ) values (
                                instance_id,
                                model_id,
                                new.legacyid,
                                now()
                            );
                        end if;
                        insert into bulk_index_queue values (resourceinstanceid, current_timestamp) on conflict do nothing;
                        insert into edit_log (
                            resourceclassid,
                            resourceinstanceid,
                            edittype,
                            timestamp,
                            note,
                            transactionid
                        ) values (
                            model_id,
                            instance_id,
                            edit_type,
                            now(),
                            'loaded via SQL backend',
                            transaction_id
                        );
                        return new;
                    end if;
                end;
            $$ language plpgsql;
    """

    operations = [
        django_migrate_sql.operations.CreateSQL(
            name="__arches_instance_view_update",
            sql="\ncreate or replace function __arches_instance_view_update() returns trigger as\n$$\ndeclare\n    view_namespace                       text;\n    model_id                             uuid;\n    instance_id                          uuid;\n    transaction_id                       uuid;\n    resource_instance_lifecycle_state_id uuid;\n    edit_type                            text;\nbegin\n    view_namespace = format('%s.%s', tg_table_schema, tg_table_name);\n    select obj_description(view_namespace::regclass, 'pg_class') into model_id;\n    if (TG_OP = 'DELETE') then\n        delete from public.resource_instances where resourceinstanceid = old.resourceinstanceid;\n        insert into bulk_index_queue (resourceinstanceid, createddate)\n        values (old.resourceinstanceid, current_timestamp)\n        on conflict do nothing;\n        insert into edit_log (resourceclassid,\n                              resourceinstanceid,\n                              edittype,\n                              timestamp,\n                              note,\n                              transactionid)\n        values (model_id,\n                old.resourceinstanceid,\n                'delete',\n                now(),\n                'loaded via SQL backend',\n                public.uuid_generate_v1mc());\n        return old;\n    else\n        instance_id = new.resourceinstanceid;\n        resource_instance_lifecycle_state_id = new.resource_instance_lifecycle_state_id;\n        if instance_id is null then\n            instance_id = public.uuid_generate_v1mc();\n        end if;\n\n        if (new.transactionid is null) then\n            transaction_id = public.uuid_generate_v1mc();\n        else\n            transaction_id = new.transactionid;\n        end if;\n\n        if (TG_OP = 'UPDATE') then\n            edit_type = 'edit';\n            if (transaction_id = old.transactionid) then\n                transaction_id = public.uuid_generate_v1mc();\n            end if;\n            update public.resource_instances\n            set createdtime                          = new.createdtime,\n                legacyid                             = new.legacyid,\n                resource_instance_lifecycle_state_id = new.resource_instance_lifecycle_state_id\n            where resourceinstanceid = instance_id;\n        elsif (TG_OP = 'INSERT') then\n            edit_type = 'create';\n            insert into public.resource_instances(resourceinstanceid,\n                                                  graphid,\n                                                  legacyid,\n                                                  createdtime,\n                                                  resource_instance_lifecycle_state_id)\n            values (instance_id,\n                    model_id,\n                    new.legacyid,\n                    now(),\n                    resource_instance_lifecycle_state_id);\n        end if;\n        insert into bulk_index_queue (resourceinstanceid, createddate)\n        values (instance_id, current_timestamp)\n        on conflict do nothing;\n        insert into edit_log (resourceclassid,\n                              resourceinstanceid,\n                              edittype,\n                              timestamp,\n                              note,\n                              transactionid)\n        values (model_id,\n                instance_id,\n                edit_type,\n                now(),\n                'loaded via SQL backend',\n                transaction_id);\n        return new;\n    end if;\nend;\n$$ language plpgsql;\n",
            reverse_sql=reverse,
        ),
    ]
