# Generated by Django 5.2.5 on 2025-08-21 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12284_resource_fields_read_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("identifier", models.TextField()),
                ("source", models.TextField()),
                ("identifier_type", models.TextField(blank=True)),
                (
                    "resourceid",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_identifiers",
                        to="models.resourceinstance",
                    ),
                ),
            ],
            options={
                "db_table": "resource_identifiers",
                "managed": True,
            },
        ),
    ]
