# Generated by Django 5.2.10 on 2026-02-10 20:00

import django_migrate_sql.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12557_add_language_datatype"),
    ]

    migrations.operations.special.SeparateDatabaseAndState(
        state_operations=[
            django_migrate_sql.operations.CreateSQL(
                name="__arches_check_tile_cardinality_violation_for_load",
                sql="\nCREATE OR REPLACE PROCEDURE public.__arches_check_tile_cardinality_violation_for_load(load_id uuid)\nAS $$\n    UPDATE load_staging\n        SET error_message = 'excess tile error', passes_validation = false\n        WHERE loadid = load_id\n        AND operation = 'insert'\n        AND (resourceid, nodegroupid, COALESCE(parenttileid::text, '')) IN (\n            SELECT t.resourceinstanceid, t.nodegroupid, COALESCE(t.parenttileid::text, '')\n                FROM tiles t, node_groups ng\n                WHERE t.nodegroupid = ng.nodegroupid\n                AND ng.cardinality = '1'\n            UNION\n            SELECT ls.resourceid, ls.nodegroupid, COALESCE(ls.parenttileid::text, '')\n                FROM load_staging ls, node_groups ng\n                WHERE ls.nodegroupid = ng.nodegroupid\n                AND ng.cardinality = '1'\n                GROUP BY ls.resourceid, ls.nodegroupid, COALESCE(ls.parenttileid::text, ''), ls.loadid\n                HAVING count(*) > 1\n                AND ls.loadid = load_id\n        );\n$$ LANGUAGE SQL;",
                reverse_sql="drop procedure __arches_check_tile_cardinality_violation_for_load;",
            ),
        ]
    )
