# Generated by Django 5.2.12 on 2026-05-29 17:23

import django_migrate_sql.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "12587_move_default_value_to_node_config"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loadstaging",
            index=models.Index(
                fields=["resourceid", "nodegroup"],
                name="load_stagin_resourc_72c547_idx",
            ),
        ),
    ]
