# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '2707_datepicker_widget_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilesurveymodel',
            name='datadownload',
            field=models.BooleanField(default=False),
        ),
    ]
