# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 12:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '2714_mobilesurveymodel_bounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilesurveymodel',
            name='datadownloadconfig',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{"download":false, "count":1000, "resources":[]}', null=True),
        ),
        migrations.RemoveField(
            model_name='mobilesurveymodel',
            name='datadownload',
        ),
    ]
