# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-07 15:17


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "4658_adds_nodevalue_type_widget_config"),
    ]

    def forwards_func(apps, schema_editor):
        pass

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
