# Generated by Django 2.2.9 on 2020-03-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '5935_2way_sync'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceinstance',
            options={'managed': True, 'permissions': (('no_access_to_resourceinstance', 'No Access'),)},
        ),
    ]
