# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 15:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '2891_tile_qa_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provisionaledit',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='provisionaledit',
            name='prototile',
        ),
        migrations.RemoveField(
            model_name='provisionaledit',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='provisionaledit',
            name='tile',
        ),
        migrations.AddField(
            model_name='tilemodel',
            name='provisionaledits',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='provisionaledits', null=True),
        ),
        migrations.DeleteModel(
            name='ProvisionalEdit',
        ),
    ]
