# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-01 15:02


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '4679_resource_editor_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tile',
            field=models.ForeignKey(db_column='tileid',
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='models.TileModel'),
        ),
    ]
