# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 16:35


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '2293_recent_edits'),
    ]

    operations = [
        migrations.AddField(
            model_name='editlog',
            name='newprovisionalvalue',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='newprovisionalvalue', null=True),
        ),
        migrations.AddField(
            model_name='editlog',
            name='oldprovisionalvalue',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='oldprovisionalvalue', null=True),
        )
    ]
