# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 20:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "2974_provisionaledits_in_editlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapMarker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("url", models.TextField()),
            ],
            options={
                "db_table": "map_markers",
                "managed": True,
            },
        ),
    ]
