# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 13:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '3385_add_provisional_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='sortorder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
