# Generated by Django 2.2.8 on 2019-12-10 16:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "5613_notification_type"),
    ]

    operations = [
        migrations.AlterField(model_name="ontology", name="path", field=models.TextField(blank=True, null=True),),
        migrations.AddField(
            model_name="ontology", name="namespaces", field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
