# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 11:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '3601_remove_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphmodel',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='config', default={}),
        ),
        migrations.AddField(
            model_name='graphmodel',
            name='template',
            field=models.ForeignKey(
                db_column='templateid',
                default='50000000-0000-0000-0000-000000000001',
                on_delete=django.db.models.deletion.CASCADE,
                to='models.ReportTemplate'
            ),
        ),
        migrations.RunSQL(
            """
                update graphs
                set templateid = r.templateid, config = r.config
                from reports r where r.graphid = graphs.graphid and r.active = true;
            """,
            ""
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
