# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 14:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "3724_report_manager_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardmodel",
            name="cssclass",
            field=models.TextField(blank=True, null=True),
        ),
    ]
