# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-23 15:43


from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '3789_card_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='component',
            field=models.ForeignKey(db_column='componentid', default=uuid.UUID('f05e4d3a-53c1-11e8-b0ea-784f435179ea'), on_delete=django.db.models.deletion.SET_DEFAULT, to='models.CardComponent'),
        ),
    ]
