# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 12:44


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '4273_provisional_edit_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilesurveymodel',
            name='datadownloadconfig',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{"download":false, "count":100, "resources":[], "custom":null}', null=True),
        ),
    ]
