# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-023-05 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '4352_format_config_number_widget'),
    ]

    operations = [
        migrations.RunSQL(
            """
            update widgets as w
            set defaultconfig = jsonb_set(defaultconfig, '{displayOnlySelectedNode}', to_jsonb(false), true)
            where w.name = 'node-value-select';
            """,
            """
            update widgets as w
            set defaultconfig = defaultconfig - 'displayOnlySelectedNode'
            where w.name = 'node-value-select';
            """)
        ]
