# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-023-05 14:40


from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("models", "4662_workflow_plugin"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DELETE FROM d_data_types WHERE datatype IN ('iiif-drawing', 'csv-chart-json')
            """,
            """
            INSERT INTO d_data_types(datatype,
                iconclass,
                modulename,
                classname,
                defaultconfig,
                configcomponent,
                configname,
                isgeometric,
                defaultwidget)
            VALUES ('csv-chart-json',
                'fa fa-line-chart',
                'datatypes.py',
                'CSVChartJsonDataType',
                null,
                null,
                null,
                FALSE,
                '10000000-0000-0000-0000-000000000020'
            );
            INSERT INTO d_data_types(datatype,
                iconclass,
                modulename,
                classname,
                defaultconfig,
                configcomponent,
                configname,
                isgeometric,
                defaultwidget)
            VALUES ('iiif-drawing',
                'fa fa-file-code-o',
                'datatypes.py',
                'IIIFDrawingDataType',
                '{"rdmCollection": null}',
                'views/components/datatypes/concept',
                'concept-datatype-config',
                FALSE,
                '10000000-0000-0000-0000-000000000022');
            """,
        )
    ]
