# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-023-05 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '4665_remove_disco_widgets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IIIFManifest',
        ),
    ]
