# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-08 19:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '4684_tabbed_report_template'),
    ]

    operations = [
        migrations.RunSQL(
                        """
                        UPDATE report_templates SET defaultconfig = '{
                          "tabs": [
                            {
                              "name": "New Tab",
                              "icon": "fa-map-marker",
                              "nodegroup_ids": []
                            }
                          ]
                        }' WHERE templateid = '50000000-0000-0000-0000-000000000004';
                        """,
                        """
                        select * from report_templates
                        """
        )]
