# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-08 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '4684_tabbed_report_template'),
    ]

    operations = [
        migrations.RunSQL(
                        """
                        update report_templates set defaultconfig = '{"tabs": []}'
                        where templateid = '50000000-0000-0000-0000-000000000004'
                        """,
                        """
                        select * from report_templates
                        """
        )]
