# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-08 19:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "4907_grouping_card_component"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE report_templates SET defaultconfig = defaultconfig || '{"activeTabIndex":0}' WHERE templateid = '50000000-0000-0000-0000-000000000004';
            UPDATE graphs SET config = config || '{"activeTabIndex":0}' WHERE templateid = '50000000-0000-0000-0000-000000000004';
            """,
            """
            UPDATE report_templates SET defaultconfig = defaultconfig - 'activeTabIndex' WHERE templateid = '50000000-0000-0000-0000-000000000004';
            UPDATE graphs SET config = config - 'activeTabIndex' WHERE templateid = '50000000-0000-0000-0000-000000000004';
            """,
        )
    ]
