# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-17 19:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '4375_add_unique_constraint_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchComponent',
            fields=[
                ('searchcomponentid', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('icon', models.TextField(default=None)),
                ('modulename', models.TextField(blank=True, null=True)),
                ('classname', models.TextField(blank=True, null=True)),
                ('componenttype', models.TextField()),
                ('componentpath', models.TextField(unique=True)),
                ('componentname', models.TextField(unique=True)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sortorder', models.IntegerField(blank=True, default=None, null=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'search_compnent',
                'managed': True,
            },
        ),
    ]
