# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-09 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '4670_maplayer_legend'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO card_components(componentid, name, description, component, componentname, defaultconfig)
                VALUES ('2f9054d8-de57-45cd-8a9c-58bbb1619030', 'Grouping Card', 'A card component that groups sibling cards together into one form.', 'views/components/cards/grouping', 'grouping-card-component', '{"groupedCardIds": []}');
        """,
        """
            DELETE FROM card_components WHERE componentid = '2f9054d8-de57-45cd-8a9c-58bbb1619030';
        """),
    ]