# Generated by Django 2.2.6 on 2019-11-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("models", "5476_search_export")]

    operations = [
        migrations.AlterModelOptions(name="plugin", options={"managed": True}),
        migrations.AlterField(
            model_name="graphmodel",
            name="template",
            field=models.ForeignKey(
                db_column="templateid",
                default="50000000-0000-0000-0000-000000000001",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="models.ReportTemplate",
            ),
        ),
    ]
