# Generated by Django 2.2.6 on 2019-10-28 18:07

import arches.app.models.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("models", "5407_remove_tileserver_configs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilesurveymodel",
            name="datadownloadconfig",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=arches.app.models.models.getDataDownloadConfigDefaults,
                null=True,
            ),
        ),
    ]
