# Generated by Django 2.2.6 on 2019-11-15 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("models", "5533_user_tasks")]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, editable=True)),
                ("message", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "notifications", "managed": True},
        )
    ]
