# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-17 19:51

import os
import uuid
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [("models", "5345_report_template_on_delete")]

    operations = [
        migrations.RunSQL(
            """
            insert into search_component (
                "searchcomponentid",
                "name",
                "icon",
                "modulename",
                "classname",
                "type",
                "componentpath",
                "componentname",
                "sortorder",
                "enabled")
            values ('9c6a5a9c-a7ec-48d2-8a25-501b55b8eff6',
                'Search Export',
                'fa fa-download',
                'search_export.py',
                'SearchExport',
                'popup',
                'views/components/search/search-export',
                'search-export',
                '3',
                true)
            """,
            """
            delete from search_component where searchcomponentid = '9c6a5a9c-a7ec-48d2-8a25-501b55b8eff6';
            """,
        )
    ]
