# Generated by Django 2.2.6 on 2019-12-03 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '5475_update_geom_mv'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('typeid', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('email_template', models.TextField(blank=True, null=True)),
                ('email_notify', models.BooleanField(default=False)),
                ('web_notify', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notification_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserXNotificationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('email_notify', models.BooleanField(default=False)),
                ('web_notify', models.BooleanField(default=False)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.NotificationType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_x_notification_types',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.NotificationType'),
        ),
    ]
