# Generated by Django 2.2.9 on 2020-04-30 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '6019_node_config_for_resource_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcexresource',
            name='inverserelationshiptype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcexresource',
            name='tileid',
            field=models.ForeignKey(blank=True, db_column='tileid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resxres_tile_id', to='models.TileModel'),
        ),
    ]
