# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-17 19:51

import os
import uuid
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [("models", "5967_related_resource_map_card_feature_editing")]

    operations = [
        migrations.RunSQL(
            """
            update d_data_types set defaultconfig = jsonb '{"dateFormat":"YYYY-MM-DD", "viewMode":"days"}' where datatype = 'date';
            """,
            """
            update d_data_types set defaultconfig = null where datatype = 'date';
            """,
        )
    ]
