# Generated by Django 2.2.13 on 2020-10-02 00:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '7262_report_template_data_fetch_bool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardxnodexwidget',
            old_name='config',
            new_name='config_en',
        ),
        migrations.AddField(
            model_name='cardxnodexwidget',
            name='config_de',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardxnodexwidget',
            name='config_en_gb',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardxnodexwidget',
            name='config_es',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
