# Generated by Django 2.2.13 on 2020-09-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '6492_add_date_datatype_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='identifier',
            field=models.TextField(blank=True, null=True),
        ),
    ]
