# Generated by Django 2.2.13 on 2020-10-02 01:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '6493_auto_20201002_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardxnodexwidget',
            old_name='label',
            new_name='label_en',
        ),
        migrations.AddField(
            model_name='cardxnodexwidget',
            name='label_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardxnodexwidget',
            name='label_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardxnodexwidget',
            name='label_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardxnodexwidget',
            name='config_en',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
