# Generated by Django 2.2.13 on 2020-10-02 19:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '6494_auto_20201002_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardmodel',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='name_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='name_en_gb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='name_es',
            field=models.TextField(blank=True, null=True),
        )
    ]
