# Generated by Django 2.2.13 on 2020-10-05 17:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '6495_auto_20201002_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='name_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardxnodexwidget',
            name='config_ar',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardxnodexwidget',
            name='label_ar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
