# Generated by Django 2.2.13 on 2020-10-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '6492_add_date_datatype_configs'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('name', 'nodegroup'), name='unique_nodename_nodegroup'),
        ),
    ]
