# Generated by Django 2.2.13 on 2020-10-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "6727_map_layer_configs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="function",
            name="component",
            field=models.TextField(blank=True, null=True),
        ),
    ]
