# Generated by Django 2.2.13 on 2020-11-10 18:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "6839_widget_disabled_configs"),
    ]

    operations = [
        migrations.AddField(
            model_name="iiifmanifest",
            name="manifest",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
