# Generated by Django 2.2.13 on 2020-12-05 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '6838_add_manifest_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestImage',
            fields=[
                ('imageid', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='cantaloupe')),
            ],
            options={
                'db_table': 'manifest_images',
                'managed': True,
            },
        ),
    ]
