# Generated by Django 2.2.28 on 2022-12-20 20:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '7128_resource_instance_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceTracker',
            fields=[
                ('eventid', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('eventname', models.TextField(blank=True, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('eventdurationsec', models.IntegerField()),
            ],
            options={
                'db_table': 'performance_tracker',
                'managed': True,
            },
        ),
    ]
