# Generated by Django 2.2.13 on 2021-05-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '7262_report_template_data_fetch_bool'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='node',
            name='unique_nodename_nodegroup',
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='name_ar',
            field=models.TextField(blank=True, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='name_de',
            field=models.TextField(blank=True, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='name_en',
            field=models.TextField(blank=True, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='name_en_gb',
            field=models.TextField(blank=True, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='name_es',
            field=models.TextField(blank=True, null=True, verbose_name='name'),
        )
    ]
