# Generated by Django 2.2.13 on 2021-07-01 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("models", "7442_delete_manifest_images_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="editlog",
            name="transactionid",
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
