# Generated by Django 2.2.13 on 2021-10-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '7128_resource_instance_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('default_direction', models.TextField(choices=[('ltr', 'Left to Right'), ('rtl', 'Right to Left')], default='ltr')),
                ('scope', models.TextField(choices=[('system', 'System Scope'), ('data', 'Data Scope')], default='system')),
            ],
            options={
                'db_table': 'languages',
                'managed': True,
            },
        ),
    ]
