# Generated by Django 2.2.13 on 2021-10-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '7128_resource_instance_filter'),
        ('models', '7783_resource_publish'),
    ]

    operations = [
    ]
