# Generated by Django 2.2.13 on 2021-03-19 20:17
from arches.app.models.fields.i18n import I18n_TextField
from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("models", "7798_i18n_cards"),
    ]

    sql = """
        SET CONSTRAINTS ALL IMMEDIATE;
        UPDATE public.widgets SET name=json_build_object('{0}', name);
        UPDATE public.widgets SET helptext=json_build_object('{0}', helptext);
        SET CONSTRAINTS ALL DEFERRED;
    """.format(
        settings.LANGUAGE_CODE
    )

    reverse_sql = """
        UPDATE public.widgets SET name=name::jsonb->>'{0}'::text;
        UPDATE public.widgets SET helptext=helptext::jsonb->>'{0}'::text;
    """.format(
        settings.LANGUAGE_CODE
    )

    operations = [
        migrations.RunSQL(sql, reverse_sql),
        migrations.AlterField(
            model_name="widget",
            name="name",
            field=I18n_TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="widget",
            name="helptext",
            field=I18n_TextField(blank=True, null=True),
        ),
    ]
