# Generated by Django 2.2.13 on 2021-03-19 20:17
from arches.app.models.fields.i18n import I18n_TextField
from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('models', '7128_resource_instance_filter'),
    ]

    sql = """
        UPDATE public.cards SET name=CONCAT('{"%s":"',name,'"}'); 
        UPDATE public.cards SET description=CONCAT('{"%s":"',description,'"}'); 
        UPDATE public.cards SET instructions=CONCAT('{"%s":"',instructions,'"}'); 
        UPDATE public.cards SET helptitle=CONCAT('{"%s":"',helptitle,'"}'); 
        UPDATE public.cards SET helptext=CONCAT('{"%s":"',helptext,'"}');
    """ % (settings.LANGUAGE_CODE,settings.LANGUAGE_CODE,settings.LANGUAGE_CODE,settings.LANGUAGE_CODE,settings.LANGUAGE_CODE )


    reverse_sql = """
        UPDATE public.cards SET name=name::jsonb->>'%s'::text;
        UPDATE public.cards SET description=description::jsonb->>'%s'::text;
        UPDATE public.cards SET instructions=instructions::jsonb->>'%s'::text;
        UPDATE public.cards SET helptitle=helptitle::jsonb->>'%s'::text;
        UPDATE public.cards SET helptext=helptext::jsonb->>'%s'::text;
    """ % (settings.LANGUAGE_CODE,settings.LANGUAGE_CODE,settings.LANGUAGE_CODE,settings.LANGUAGE_CODE,settings.LANGUAGE_CODE)

    operations = [
        migrations.RunSQL(sql, reverse_sql),
        migrations.AlterField(
            model_name='cardmodel',
            name='name',
            field=I18n_TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='description',
            field=I18n_TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='instructions',
            field=I18n_TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='helptitle',
            field=I18n_TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='helptext',
            field=I18n_TextField(blank=True, null=True),
        ),
    ]