# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 15:53


from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '9055_add_branch_publication_to_node'),
    ]

    def add_permissions(apps, schema_editor, with_create_permissions=True):
        db_alias = schema_editor.connection.alias
        Group = apps.get_model("auth", "Group")
        User = apps.get_model("auth", "User")
        resource_exporter_group = Group.objects.using(db_alias).create(name='Resource Exporter')

        try:
            admin_user = User.objects.using(db_alias).get(username='admin')
            admin_user.groups.add(resource_exporter_group)
            print('added admin group')
        except Exception as e:
            print(e)

    def remove_permissions(apps, schema_editor, with_create_permissions=True):
        db_alias = schema_editor.connection.alias
        Group = apps.get_model("auth", "Group")
        resource_exporter_group = Group.objects.using(db_alias).get(name='Resource Exporter')
        User = apps.get_model("auth", "User")

        try:
            admin_user = User.objects.using(db_alias).get(username='admin')
            admin_user.groups.remove(resource_exporter_group)
            print('removed admin group')
        except:
            pass

        resource_exporter_group.delete()

    operations = [
        migrations.RunPython(add_permissions, reverse_code=remove_permissions),
    ]
