# Generated by Django 2.2.13 on 2021-12-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "7128_resource_instance_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mfa_hash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
