# Generated by Django 2.2.24 on 2022-03-23 03:47

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '8042_2_adds_display_label_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialView',
            fields=[
                ('spatialviewid', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('schema', models.TextField(default='public')),
                ('name', models.TextField(unique=True)),
                ('slug', models.TextField(unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('description', models.TextField()),
                ('ismixedgeometrytypes', models.BooleanField(default=False)),
                ('attributenodes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='attributenodes', null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('geometrynodeid', models.ForeignKey(db_column='geometrynodeid', on_delete=django.db.models.deletion.CASCADE, to='models.Node')),
            ],
            options={
                'db_table': 'spatial_views',
                'managed': True,
            },
        ),
    ]
