# Generated by Django 3.2.14 on 2022-07-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '8140_django_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='sortorder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
