# Generated by Django 2.2.13 on 2022-02-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '7128_resource_instance_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maplayer',
            options={'default_permissions': (), 'managed': True, 'permissions': (('no_access_to_maplayer', 'No access to map layer'),)},
        ),
        migrations.AlterModelOptions(
            name='mapsource',
            options={'default_permissions': (), 'managed': True, 'permissions': (('no_access_to_mapsource', 'No access to map source'),)},
        ),
    ]
