# Generated by Django 2.2.13 on 2022-02-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "8085_relational_data_model_handle_dates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maplayer",
            options={"default_permissions": (), "managed": True, "permissions": (("no_access_to_maplayer", "No access to map layer"),)},
        ),
        migrations.AlterModelOptions(
            name="mapsource",
            options={"default_permissions": (), "managed": True, "permissions": (("no_access_to_mapsource", "No access to map source"),)},
        ),
    ]
