# Generated by Django 2.2.24 on 2022-06-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "8301_descriptors"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="hascustomalias",
            field=models.BooleanField(default=False),
        ),
    ]
