# Generated by Django 2.2.24 on 2022-05-12 17:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "8403_relational_data_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceinstance",
            name="descriptors",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourceinstance",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
