# Generated by Django 2.2.24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "8449_filter_warning_etl_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="loadevent",
            name="indexed_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
