# Generated by Django 3.2.15 on 2022-11-30 16:31

import arches.app.models.fields.i18n
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "8974_rr_load_performance_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphmodel",
            name="original_graphid",
            field=models.UUIDField(blank=True, null=True),
        )
    ]
