# Generated by Django 3.2.18 on 2023-06-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "12586_tile_cardinality_check"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataMigration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app", models.TextField()),
                ("name", models.TextField()),
                ("applied", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_migrations",
                "managed": True,
            },
        )
    ]
