# Generated by Django 3.2.18 on 2023-06-16 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '9477_fix_for_spatial_view_dbf_function_edtf_displaying_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.TextField()),
                ('name', models.TextField()),
                ('operation', models.TextField()),
                ('resource_instance_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(blank=True), size=None)),
                ('applied', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_migrations',
                'managed': True,
            },
        )
    ]
