# Generated by Django 3.2.15 on 2023-04-07 18:52

import arches.app.models.fields.i18n
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "9219_divide_individual_editors"),
    ]

    operations = [
        migrations.AddField(
            model_name="loadevent",
            name="taskid",
            field=models.TextField(blank=True, null=True),
        ),
    ]
