# Generated by Django 4.2.4 on 2023-11-10 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('models', '9334_populate_iiifmanifest_globalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iiifmanifest',
            name='globalid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
