# Generated by Django 4.2.4 on 2023-11-10 12:09

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    IIIFManifest = apps.get_model("models", "IIIFManifest")
    for row in IIIFManifest.objects.all():
        row.globalid = uuid.uuid4()
        row.save(update_fields=["globalid"])


class Migration(migrations.Migration):
    dependencies = [
        ("models", "9334_add_iiifmanifest_globalid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]