# Generated by Django 4.2.4 on 2023-11-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '9333_file_type_image_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='iiifmanifest',
            name='globalid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
