# Generated by Django 3.2.15 on 2023-03-31 15:48

import arches.app.models.fields.i18n
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("models", "9370_concept_relation"),
    ]

    operations = [
        migrations.AddField(
            model_name="iiifmanifest",
            name="transactionid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
