# Generated by Django 3.2.18 on 2023-06-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "9466_immutable_branches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tilemodel",
            name="nodegroup",
        ),
        migrations.AddField(
            model_name="tilemodel",
            name="nodegroup_id",
            field=models.UUIDField(db_column="nodegroupid", null=True),
        ),
    ]
