# Generated by Django 4.2.13 on 2024-06-20 15:36

from django.db import migrations, models
import django.db.models.fields.json
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ("models", "9525_add_published_graph_edits"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                django.db.models.functions.comparison.Cast(
                    django.db.models.fields.json.KeyTextTransform(
                        "controlledList", "config"
                    ),
                    output_field=models.UUIDField(),
                ),
                name="lists_reffed_by_node_idx",
            ),
        ),
    ]
