# Generated by Django 3.2.18 on 2023-05-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "9219_update_load_event_task"),
    ]

    add_help_to_plugin = """
            UPDATE plugins
            SET config = config || '{"showHelp": false, "helpTemplate": ""}';

            UPDATE plugins
            SET config = jsonb_set(config, '{helpTemplate}', '"plugins-help"')
            WHERE name = 'Bulk Data Manager';
            """
    remove_help_from_plugin = """
            UPDATE plugins
            SET config = config - 'showHelp' - 'helpTemplate';
            """
    add_help_to_etl_module = """
            UPDATE etl_modules
            SET config = config || '{"showHelp": false, "helpTemplate": "", "helpSortOrder": ""}';
            """
    remove_help_from_etl_module = """
            UPDATE etl_modules
            SET config = config - 'showHelp' - 'helpTemplate' - 'helpSortOrder';
            """

    operations = [
        migrations.RunSQL(
            add_help_to_plugin,
            remove_help_from_plugin
        ),
        migrations.RunSQL(
            add_help_to_etl_module,
            remove_help_from_etl_module
        ),
    ]
