# Generated by Django 3.2.15 on 2023-05-25 16:25

import arches.app.models.fields.i18n
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "9563_temporary_files"),
    ]

    operations = [
        # ordering not defined in maplayer migration #8928
        migrations.AlterModelOptions(
            name="maplayer",
            options={"managed": True, "ordering": ("sortorder", "name")},
        ),
        # last modified to change to i18n json field in model - no migration ever generated.
        migrations.AlterField(
            model_name="cardxnodexwidget",
            name="config",
            field=arches.app.models.fields.i18n.I18n_JSONField(
                blank=True, db_column="config", null=True
            ),
        ),
        # last modified to change to i18n json field in model - no migration ever generated.
        migrations.AlterField(
            model_name="ddatatype",
            name="defaultconfig",
            field=arches.app.models.fields.i18n.I18n_JSONField(
                blank=True, db_column="defaultconfig", null=True
            ),
        ),
        # last modified to change to i18n json field in model - no migration ever generated.
        migrations.AlterField(
            model_name="node",
            name="config",
            field=arches.app.models.fields.i18n.I18n_JSONField(
                blank=True, db_column="config", null=True
            ),
        ),
        # following two fields are specified in their respective migrations as legacy contrib jsonb type.
        # jsonb is automatic for models.JSONField and these are basically noops.
        migrations.AlterField(
            model_name="publishedgraph",
            name="serialized_graph",
            field=models.JSONField(blank=True, db_column="serialized_graph", null=True),
        ),
        migrations.AlterField(
            model_name="resourceinstance",
            name="descriptors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
