# Generated by Django 3.2.15 on 2023-05-25 16:25

import arches.app.models.fields.i18n
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "9566_migration_fix"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO d_relation_types VALUES ('inverseOf', 'Mapping Properties', 'skos');
            """,
            """
            DELETE FROM relations WHERE relationtype = 'inverseOf';
            DELETE FROM d_relation_types WHERE relationtype = 'inverseOf';
            """,
        ),
    ]
