# Generated by Django 3.2.19 on 2023-10-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '9477_fix_for_spatial_view_dbf_function_edtf_displaying_null'),
        ('models', '9604_relational_data_model_handle_user_accounts'),
    ]

    operations = [
    ]
