# Generated by Django 3.2.20 on 2023-08-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "9746_related_resource_post_save_bug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maplayer",
            options={
                "default_permissions": (),
                "managed": True,
                "ordering": ("sortorder", "name"),
                "permissions": (
                    ("no_access_to_maplayer", "No Access"),
                    ("read_maplayer", "Read"),
                    ("write_maplayer", "Create/Update"),
                    ("delete_maplayer", "Delete"),
                ),
            },
        ),
    ]
