# Generated by Django 4.2.4 on 2023-11-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "9944_improve_refresh_relationship_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="thumbnail_data",
            field=models.BinaryField(null=True),
        )
    ]
