# Generated by Django 4.2.8 on 2023-12-19 16:48

import arches.app.models.fields.i18n
import arches.app.utils.betterJSONSerializer
from django.db import migrations, models
import django.db.models.deletion


def explode_configs(apps, schema_editor):
    DomainValue = apps.get_model("models", "DomainValue")
    Node = apps.get_model("models", "Node")

    domain_values_for_insert = []
    for node in Node.objects.filter(datatype__in=("domain-value", "domain-value-list")):
        for option in node.config["options"]:
            domain_values_for_insert.append(
                DomainValue(
                    pk=option["id"],
                    node=node,
                    text=option["text"],
                    selected=option["selected"],
                    fn=node.config["i18n_config"]["fn"],
                )
            )
        node.config = {}
        # cannot bulk_update(), raises NotImplementedError
        node.save(update_fields=["config"])

    DomainValue.objects.bulk_create(domain_values_for_insert)

    # Preserve defaultconfig on DDataType for sake of front end graph tree


def implode_configs(apps, schema_editor):
    DomainValue = apps.get_model("models", "DomainValue")

    nodes_for_update = []
    for option in DomainValue.objects.all().select_related():
        if "options" not in option.node.config:
            option.node.config["options"] = []
        option.node.config["i18n_config"] = {"fn": option.fn}
        option.node.config["options"].append(
            {
                "id": str(option.pk),
                "text": dict(option.text),
                "selected": option.selected,
            }
        )
        nodes_for_update.append(option.node)

    for node in nodes_for_update:
        # cannot bulk_update(), raises NotImplementedError
        node.save(update_fields=["config"])

    # Preserve defaultconfig on DDataType for sake of front end graph tree


class Migration(migrations.Migration):
    dependencies = [
        ("models", "9945_file_thumbnail_bin_file_thumbnail_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainValue",
            fields=[
                ("domainvalueid", models.UUIDField(primary_key=True, serialize=False)),
                ("text", arches.app.models.fields.i18n.I18n_JSONField(encoder=arches.app.utils.betterJSONSerializer.JSONSerializer)),
                ("selected", models.BooleanField()),
                (
                    "node",
                    models.ForeignKey(
                        db_column="nodeid", on_delete=django.db.models.deletion.CASCADE, related_name="domain_values", to="models.node"
                    ),
                ),
                ("fn", models.CharField(default="arches.app.datatypes.datatypes.DomainDataType", max_length=127)),
            ],
            options={
                "db_table": "domain_value",
                "managed": True,
                "indexes": [models.Index(fields=["node"], name="domain_valu_nodeid_dc9286_idx")],
            },
        ),
        migrations.RunPython(explode_configs, implode_configs),
    ]
