# Generated by Django 4.2.23 on 2025-07-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("models", "11499_add_editlog_resourceinstance_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="WidgetMapping",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("component", models.TextField(unique=True)),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="models.widget"
                    ),
                ),
            ],
            options={
                "db_table": "widget_mappings",
                "managed": True,
            },
        ),
    ]
