# Generated by Django 5.2b1 on 2025-03-04 13:37

from django.db import migrations


class Migration(migrations.Migration):
    """There must be an initial migration for the proxy models to work."""

    dependencies = [
        ("models", "11499_add_editlog_resourceinstance_idx"),  # last 7.6 migration
    ]

    operations = []
