# Generated by Django 4.2.14 on 2024-07-23 10:51

import textwrap
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "10999_update_principaluser"),
        ("arches_references", "0002_etl_collections_to_controlled_lists"),
    ]

    create_index = textwrap.dedent(
        """
        CREATE INDEX "lists_reffed_by_node_idx" ON "nodes" (
            ((("config" ->> 'controlledList'))::uuid)
        );
    """
    )
    remove_index = 'DROP INDEX IF EXISTS "lists_reffed_by_node_idx";'

    operations = [
        migrations.CreateModel(
            name="NodeProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("models.node",),
        ),
        migrations.RunSQL(create_index, remove_index),
    ]
