# Generated by Django 5.2 on 2025-05-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arches_controlled_lists", "0002_etl_collections_to_controlled_lists"),
    ]

    operations = [
        migrations.RenameField(
            model_name="list",
            old_name="search_only",
            new_name="searchable",
        ),
    ]
