# Generated by Django 4.2.30 on 2026-06-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11499_add_editlog_resourceinstance_idx"),
        ("arches_component_lab", "0003_add_pk_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widgetmapping",
            name="component",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="widgetmapping",
            unique_together={("widget", "component")},
        ),
    ]
