# Generated by Django 4.2.14 on 2024-07-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arches_references", "0003_add_node_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="uri",
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
