drop function if exists __arches_slugify;
drop function if exists __arches_get_node_value_sql;
drop function if exists __arches_create_nodegroup_view;
drop function if exists __arches_create_resource_model_views;
drop function if exists __arches_create_branch_views;
drop function if exists __arches_tile_view_update;
drop function if exists __arches_get_json_data_for_view;
drop function if exists __arches_get_parent_id_for_view;
drop function if exists __arches_instance_view_update;
